[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'sophacles/vim-processing'

[[plugins]]
repo = 'vim-scripts/fcitx.vim'
if = '''! has('kaoriya')'''

[[plugins]]
repo = 'vim-latex/vim-latex'

